services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  gate-simulator:
    build:
      context: ./gate-simulator
    container_name: bank_simulator
    ports:
      - '9999:9999'
    working_dir: /app
    command: npm start
    volumes:
      - ./gate-simulator:/app

